title = "Ian Andwati"
description = "Ian's website."
base_url = "https://andwati.github.io"
minify_html = true
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml"]
taxonomies = [{ name = "tags", feed = false }]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[link_checker]
skip_prefixes = [""]
skip_anchor_prefixes = ["https://github.com/"]

[extra]
author = "Ian Andwati"
meta = [
    { property = "og:title", content = "the og title" },
    { property = "og:description", content = "the og description" },
]
